services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_DEVICE_IP=${IP_ADDRESS}
      - REACT_APP_PORT=5000
    working_dir: /app
    command: bash -c "npm install && npm start"
    depends_on:
      - backend
    network_mode: "host"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    working_dir: /backend
    network_mode: "host"

networks:
  public:
    external: true
